export const tabs = {
  code: 200,
  msg: 'ok',
  data: [
    { label: '项目', name: 'project', count: 2 },
    { label: '其它', name: 'other', count: 3 },
  ],
}

export const cards = {
  code: 200,
  msg: 'ok',
  data: [
    {
      cardId: 'project-overview',
      category: 'project',
      creatorId: 'admin',
      modifierId: 'admin',
      title: '项目概况',
      description: '项目概况',
      picUrl: '项目概况',
      w: 25,
      h: 20,
    },
    {
      cardId: 'code-library-overview',
      category: 'other',
      creatorId: 'admin',
      modifierId: 'admin',
      title: '代码库概况',
      description: '代码库概况',
      picUrl: '代码库概况',
      w: 50,
      h: 12,
    },
    {
      cardId: 'product-library-overview',
      category: 'other',
      creatorId: 'admin',
      modifierId: 'admin',
      title: '制品库概况',
      description: '制品库概况',
      picUrl: '制品库概况',
      w: 50,
      h: 8,
    },
    {
      cardId: 'app-library-overview',
      category: 'other',
      creatorId: 'admin',
      modifierId: 'admin',
      title: '应用库概况',
      description: '应用库概况',
      picUrl: '应用库概况',
      w: 21,
      h: 20,
    },
    {
      cardId: 'follow-project',
      category: 'project',
      creatorId: 'admin',
      modifierId: 'admin',
      title: '重点关注项目情况',
      description: '重点关注项目情况',
      picUrl: '重点项目关注情况',
      w: 100,
      h: 12,
    },
  ],
}

export const report = {
  code: 200,
  msg: 'ok',
  data: [
    {
      cardId: 'project-overview',
      category: 'project',
      creatorId: 'admin',
      modifierId: 'admin',
      title: '项目概况',
      description: '项目概况',
      w: 26,
      h: 20,
      active: true,
      x: 0,
      y: 0,
      i: 0,
      moved: false,
    },
    {
      cardId: 'code-library-overview',
      category: 'other',
      creatorId: 'admin',
      modifierId: 'admin',
      title: '代码库概况',
      description: '代码库概况',
      w: 50,
      h: 12,
      active: true,
      x: 27,
      y: 0,
      i: 1,
      moved: false,
    },
    {
      cardId: 'product-library-overview',
      category: 'other',
      creatorId: 'admin',
      modifierId: 'admin',
      title: '制品库概况',
      description: '制品库概况',
      w: 50,
      h: 8,
      active: true,
      x: 27,
      y: 12,
      i: 2,
      moved: false,
    },
    {
      cardId: 'app-library-overview',
      category: 'other',
      creatorId: 'admin',
      modifierId: 'admin',
      title: '应用库概况',
      description: '应用库概况',
      w: 22,
      h: 20,
      active: true,
      x: 78,
      y: 0,
      i: 3,
      moved: false,
    },
    {
      cardId: 'follow-project',
      category: 'project',
      creatorId: 'admin',
      modifierId: 'admin',
      title: '重点关注项目情况',
      description: '重点关注项目情况',
      picUrl: '重点项目关注情况',
      w: 100,
      h: 12,
      active: true,
      x: 0,
      y: 20,
      i: 4,
      moved: false,
    },
  ],
}

export const report2 = {
  code: 200,
  msg: 'ok',
  data: [
    {
      cardId: 'project-overview',
      category: 'other',
      creatorId: 'admin',
      modifierId: 'admin',
      title: '项目概况',
      description: '项目概况',
      w: 26,
      h: 20,
      active: true,
      x: 0,
      y: 0,
      i: 0,
      moved: false,
    },
    {
      cardId: 'code-library-overview',
      category: 'other',
      creatorId: 'admin',
      modifierId: 'admin',
      title: '代码库概况',
      description: '代码库概况',
      w: 73,
      h: 20,
      active: true,
      x: 27,
      y: 0,
      i: 1,
      moved: false,
    },
    {
      cardId: 'product-library-overview',
      category: 'other',
      creatorId: 'admin',
      modifierId: 'admin',
      title: '制品库概况',
      description: '制品库概况',
      w: 50,
      h: 9,
      active: true,
      x: 0,
      y: 20,
      i: 2,
      moved: false,
    },
    {
      cardId: 'app-library-overview',
      category: 'other',
      creatorId: 'admin',
      modifierId: 'admin',
      title: '应用库概况',
      description: '应用库概况',
      w: 47,
      h: 9,
      active: true,
      x: 53,
      y: 20,
      i: 3,
      moved: false,
    },
    {
      cardId: 'follow-project',
      category: 'other',
      creatorId: 'admin',
      modifierId: 'admin',
      title: '重点关注项目情况',
      description: '重点关注项目情况',
      picUrl: '重点项目关注情况',
      w: 100,
      h: 12,
      active: true,
      x: 0,
      y: 29,
      i: 4,
      moved: false,
    },
  ],
}
